import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import DefaultLayout from '../../layouts/DefaultLayout'

export default function Cat() {
    const router = useRouter()
    const { id } = router.query
    const [cat, setCat] = useState(null)

    const fetchCat = async() => {
        const data = await fetch(`/api/cats/${id}`).then(res => res.json()).catch(e => {throw new Error(e)})
        setCat(data)
    }

    useEffect(() => {
        fetchCat()
    }, [])
  return (
    <>
        <DefaultLayout>
            {cat && (
                <>
                <Head>
                    <title>{`${cat.name} the cat`}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
               
                 <div className='container mt-5'>
                     <img src={cat.image.url} alt={cat.image.alt} style={{width: '300px'}} />
                    <div className='mx-5'>
                        <h1>{cat.name}</h1>
                        <p>{cat.description}</p>
                    </div>
                 </div>
    </>
            )}
        </DefaultLayout>
    </>
  )
}
